# Generated by Django 3.0.1 on 2019-12-26 14:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя и Фамилия мастера')),
                ('job', models.CharField(max_length=255, null=True, verbose_name='Специализация')),
                ('info', models.TextField(max_length=255, null=True, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='SeoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для главной')),
                ('indexDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для главной')),
                ('indexKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для главной')),
                ('servicesTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы со всеми услугами')),
                ('servicesDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы со всеми услугам')),
                ('servicesKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы со всеми услугам')),
                ('postsTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы со всеми статьями')),
                ('postsDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы со всеми статьями')),
                ('postsKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы со всеми статьями')),
                ('aboutTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы о компании')),
                ('aboutDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы о компании')),
                ('aboutKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы о компании')),
                ('yandexMetrika', models.TextField(blank=True, null=True, verbose_name='Код Яндекс метрики')),
                ('fbPixel', models.TextField(blank=True, null=True, verbose_name='Код пикселя')),
                ('yandexTAG', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код подтверждения Яндекс')),
                ('googleTAG', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код подтверждения google')),
            ],
            options={
                'verbose_name': 'Теги для статических страниц',
                'verbose_name_plural': 'Теги для статических страниц',
            },
        ),
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Вид работы')),
                ('image', models.ImageField(null=True, upload_to='services_img/', verbose_name='Изображение превью (360 x 250)')),
                ('imageHeader', models.ImageField(upload_to='', verbose_name='Изображение для бекграунда страницы с услугой (1920х560)')),
                ('topText', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст на страницу с услугой')),
                ('acc1Text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Показания')),
                ('acc2Text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Противопоказания')),
                ('name_slug', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('page_h1', models.CharField(max_length=255, null=True, verbose_name='Тег H1')),
                ('page_title', models.CharField(max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('page_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ',
            },
        ),
    ]
