# Generated by Django 3.0.1 on 2019-12-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость услуги'),
        ),
        migrations.AddField(
            model_name='servicename',
            name='shortDescr',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True, verbose_name='Короткое описание услуги (80 символов)'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='image',
            field=models.ImageField(null=True, upload_to='services_img/', verbose_name='Изображение превью (330 x 220)'),
        ),
    ]
