# Generated by Django 3.0.1 on 2019-12-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191226_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicename',
            name='isVisible',
            field=models.BooleanField(default=False, verbose_name='Отображать в нескрываемом блоке'),
        ),
    ]
