# Generated by Django 3.0.1 on 2019-12-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_servicename_isvisible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicename',
            name='shortDescr',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='Короткое описание услуги (80 символов)'),
        ),
    ]
