# Generated by Django 3.0.1 on 2019-12-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191226_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicename',
            name='imageHeader',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для бекграунда страницы с услугой (1920х560)'),
        ),
    ]
