# Generated by Django 3.0.1 on 2019-12-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='Нет данных', max_length=255, verbose_name='Имя')),
                ('userPhone', models.CharField(default='Нет данных', max_length=255, verbose_name='Телефон')),
                ('service', models.CharField(default='Нет данных', max_length=255, verbose_name='Услуга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Форма заказа звонка',
                'verbose_name_plural': 'Формы заказа звонка',
            },
        ),
    ]
