# Generated by Django 3.0.1 on 2019-12-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackorder',
            name='master',
            field=models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='callbackorder',
            name='service',
            field=models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Услуга'),
        ),
    ]
